python main_visual.py \
    --gpus='1'  \
    --lr=1e-12 \
    --batch_size=128 \
    --num_workers=8 \
    --max_epoch=20 \
    --test_interval=1.0 \
    --save_prefix='checkpoints/lrw-border-baseline/' \
    --n_class=500 \
    --dataset='lrw' \
    --border=True \
    --mixup=False \
    --label_smooth=False \
    --se=True \
    --weights='checkpoints/lrw-border-se-mixup-label-smooth-cosine-lr-wd-1e-4-acc-0.88492.pt'